import Pagination from '@/components/Pagination/Pagination'
import SinglePost from '@/components/Post/SinglePost'
import { getNumberOfPages, getPostByPage, getPostsForTopPage } from '@/lib/notionAPI'
import { GetStaticPaths, GetStaticProps } from 'next'
import Head from 'next/head'


export default function BlogPageList({postByPage,numberOfPage}:any) {


  return (
    <>
    <div className='container h-full w-full mx-auto '>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container w-full mt-16'>
        <h1 className='text-5xl font-medium text-center mb-16'>Notion Blog🚀</h1>
        <section className='sm:grid grid-cols-2 w-5/6 gap-3 mx-auto'>
        {
            postByPage.map((post:any)=>{
                return (<div key={post.id} >
              <SinglePost 
              title={post.title}
              description={post.description}
              date={post.date}
              tag={post.tags}
              slug={post.slug}
              isPagenationPage={true}
              />
            </div>)
          })
        }
        </section>
        <Pagination numberOfPage = {numberOfPage} tag={""}/>
      </main>
      
        </div>
    </>
  )
}

export const getStaticPaths:GetStaticPaths= async()=>{
  const numberOfPage = await getNumberOfPages();

    let params = [];
    for(let i = 1; i<= numberOfPage;i++){
      params.push({params : {page : i.toString()}})
    }
    return{
        paths: params,
        fallback:false
    }
}


export const getStaticProps:GetStaticProps = async(context)=>{

  const currentPage = context.params?.page;

  if (!currentPage) {
    return {
      notFound: true,
    }
  }
  const numberOfPage = await getNumberOfPages();

  const postByPage = await getPostByPage(parseInt(currentPage.toString(),10))


  return {
    props :{
      postByPage,
      numberOfPage
    },
    revalidate:60
  }
}